---
- name: Copy Flask Application Files
  copy:
    src: "{{ playbook_dir }}/roles/application/files"
    dest: "/opt/{{ Seron_application }}"
    owner: "{{ Seron }}"
    group: "{{ Seron }}"
  become: yes

- name: Install Python 3 and pip
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
  become: yes

- name: Install Flask
  pip:
    name: Flask
  become: yes

- name: Configure Flask Application
  template:
    src: application_config.j2
    dest: "/opt/{{ Seron_application}}/app.py"
  become: yes

- name: Start the Flask Application
  command: "python3 /opt/{{ Seron_application }}/app.py"
  async: 300
  poll: 0
  become: yes
  ignore_errors: yes  # Consider using a more robust method to manage the application as a service.
