---
- name: Install MongoDB
  apt:
    name: mongodb
    state: present
  become: yes

- name: Configure MongoDB
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  notify: Restart MongoDB

- name: Start MongoDB
  service:
    name: mongod
    state: started
    enabled: yes
