---
- name: Deploy Nginx, Application, and MongoDB
  hosts: app_servers
  become: yes
  vars:
    app_name: "Seron_application"
    app_owner: "Seron"
    app_group: "Seron"
  roles:
    - role: nginx
    - role: application
    - role: mongodb
